interface NPC {
  id: number;
  name: string;
  height: number;
  mass: number;
  hairColor: string;
  skinColor: string;
  eyeColor: string;
  gender: string;
  description: string;
  relations: string;
}

export const NPCs: NPC[] = [
  {
    id: 1,
    name: 'Luke Skywalker',
    height: 172,
    mass: 77,
    hairColor: 'blond',
    skinColor: 'fair',
    eyeColor: 'blue',
    gender: 'male',
    description: ``,
    relations: ``,
  },
  {
    id: 2,
    name: 'C-3PO',
    height: 167,
    mass: 75,
    hairColor: 'n/a',
    skinColor: 'gold',
    eyeColor: 'yellow',
    gender: 'n/a',
    description: ``,
    relations: ``,
  },
  {
    id: 3,
    name: 'R2-D2',
    height: 96,
    mass: 32,
    hairColor: 'n/a',
    skinColor: 'white, blue',
    eyeColor: 'red',
    gender: 'n/a',
    description: ``,
    relations: ``,
  },
  {
    id: 4,
    name: 'Darth Vader',
    height: 202,
    mass: 136,
    hairColor: 'none',
    skinColor: 'white',
    eyeColor: 'yellow',
    gender: 'male',
    description: ``,
    relations: ``,
  },
  {
    id: 5,
    name: 'Leia Organa',
    height: 150,
    mass: 49,
    hairColor: 'brown',
    skinColor: 'light',
    eyeColor: 'brown',
    gender: 'female',
    description: ``,
    relations: ``,
  },
  {
    id: 6,
    name: 'Owen Lars',
    height: 178,
    mass: 120,
    hairColor: 'brown, grey',
    skinColor: 'light',
    eyeColor: 'blue',
    gender: 'male',
    description: ``,
    relations: ``,
  },
  {
    id: 7,
    name: 'Beru Whitesun Lars',
    height: 165,
    mass: 75,
    hairColor: 'brown',
    skinColor: 'light',
    eyeColor: 'blue',
    gender: 'female',
    description: ``,
    relations: ``,
  },
  {
    id: 8,
    name: 'R5-D4',
    height: 97,
    mass: 32,
    hairColor: 'n/a',
    skinColor: 'white, red',
    eyeColor: 'red',
    gender: 'n/a',
    description: ``,
    relations: ``,
  },
  {
    id: 9,
    name: 'Biggs Darklighter',
    height: 183,
    mass: 84,
    hairColor: 'black',
    skinColor: 'light',
    eyeColor: 'brown',
    gender: 'male',
    description: ``,
    relations: ``,
  },
  {
    id: 10,
    name: 'Obi-Wan Kenobi',
    height: 182,
    mass: 77,
    hairColor: 'auburn, white',
    skinColor: 'fair',
    eyeColor: 'blue-gray',
    gender: 'male',
    description: ``,
    relations: ``,
  },
];
